name: C3 COWSAY
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_cowsay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run COWSAY
        run: |
          chmod +x ./scripts.sh
          ./scripts.sh